# Generated by Django 4.2.10 on 2024-03-03 12:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_user_profile_pic_path),
        ),
    ]
