# Generated by Django 4.2.10 on 2024-03-03 16:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecord',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
